### ISSUE TITLE
Purge only existing entries

### ISSUE THREAD

**Issue by johnnywalls** [nilp0inter/binlog#7]
It seems that the current purge method can attempt to remove entries that have already been purged.  The current list includes entries that have been acked for all readers:
https://github.com/nilp0inter/binlog/blob/94d7670e508461b0f4bfc94b5f06650a3fcab6de/binlog/connection.py#L358

This list could be also filtered by considering only existing entries, thus reducing (or even removing the need for) results counted as not_found.

**Comment by nilp0inter** [comment]
Implemented in v5.1.0. not_found will always be 0.
